openapi: 3.0.0
info:
  title: Average API
  description: Api que calcula média aritmética entre vários números.
  version: 1.0.0

paths:
  /api/average:
    post:
      summary: Média aritmética.
      description: Calcula a média aritmética.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numbers:
                  type: array
                  items:
                    type: integer
      responses:
        "200": # status code
          description: Json com status code, mensagem e média obtida
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      average:
                        type: number
        "422": # status code
          description: Json com status code, mensagem de erro de data com erros obtidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: string
